#!/usr/bin/env bash
# wiki-graph.sh — Generate Mermaid knowledge graph from Wiki cross-references
# Usage: wiki-graph.sh [wiki-path]

set -euo pipefail

WIKI_PATH="${1:-.}"
OUTPUT="$WIKI_PATH/knowledge-graph.md"

# Collect all wiki pages (excluding meta files)
pages=()
for f in "$WIKI_PATH"/*.md; do
  [ ! -f "$f" ] && continue
  base=$(basename "$f" .md)
  case "$base" in
    CLAUDE|index|log|knowledge-graph) continue ;;
  esac
  pages+=("$base")
done

page_exists() {
  local candidate="$1"
  local page
  for page in "${pages[@]}"; do
    if [ "$page" = "$candidate" ]; then
      return 0
    fi
  done
  return 1
}

if [ ${#pages[@]} -eq 0 ]; then
  echo "No wiki pages found in $WIKI_PATH"
  exit 1
fi

# Build Mermaid graph
{
  echo "---"
  echo "title: Knowledge Graph"
  echo "updated: $(date +%Y-%m-%d)"
  echo "tags: [meta, graph]"
  echo "---"
  echo ""
  echo '> TLDR: Auto-generated relationship map of all Wiki pages.'
  echo ""
  echo '```mermaid'
  echo "graph LR"

  # Emit nodes
  for page in "${pages[@]}"; do
    # Sanitize node ID: replace hyphens with underscores for Mermaid
    node_id="${page//-/_}"
    echo "  ${node_id}[\"${page}\"]"
  done

  echo ""

  # Emit edges from [[wikilinks]]
  for page in "${pages[@]}"; do
    src_id="${page//-/_}"
    # Extract all [[targets]] from the page
    grep -oh '\[\[[^]]*\]\]' "$WIKI_PATH/${page}.md" 2>/dev/null \
      | sed 's/\[\[//;s/\]\]//' \
      | sort -u \
      | while read -r target; do
          canonical_target="${target%%|*}"
          canonical_target="${canonical_target%%#*}"
          [ -z "$canonical_target" ] && continue
          page_exists "$canonical_target" || continue
          tgt_id="${canonical_target//-/_}"
          echo "  ${src_id} --> ${tgt_id}"
        done
  done

  echo '```'
  echo ""
  echo "Generated by \`wiki-graph.sh\` on $(date +%Y-%m-%d)."
} > "$OUTPUT"

# Stats
edge_count=$(grep -c ' --> ' "$OUTPUT" 2>/dev/null || echo 0)
echo "=== Knowledge Graph Generated ==="
echo "Pages:  ${#pages[@]}"
echo "Edges:  $edge_count"
echo "Output: $OUTPUT"
